/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Derived Supabase info from environment */

const envUrl = (import.meta as any).env?.VITE_SUPABASE_URL as string | undefined;
const envAnon = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY as string | undefined;

export const supabaseUrl = envUrl ?? "https://qudatjeaebentuiywftz.supabase.co";
export const publicAnonKey = envAnon ?? "";

// Helper: base URL for Edge Functions
export const supabaseFunctionsBaseUrl = `${supabaseUrl}/functions/v1`;

// Optional: expose project id if needed by code building URLs from id
export const projectId = supabaseUrl.replace(/^https?:\/\//, "").split(".")[0];